version: '3'

networks:
  app-tier:
    driver: bridge
services:
  rabbit:
   hostname: rabbitmq 
   image: rabbitmq:3-management
   networks:
    - app-tier
   ports:
    - 5672:5672
    - 15672:15672
  rest:
    image: rest
    networks:
    - app-tier
    ports:
    - "8080:8080"
  calculator:
    image: calculator
    networks:
    - app-tier 
    ports:
    - "8081:8081"

   